# first, user login and get the JWT token
# @name login
POST http://localhost:8080/api/auth/login HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}

{
    "email":"fathimah@mail.com",
    "password":"passftahimah"
}
###
# user can access profile
GET http://localhost:8080/api/user/profile HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}

###
# user get All Event
GET http://localhost:8080/api/event/all HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}

###
# user get Event
# @name getevent
GET http://localhost:8080/api/event/5 HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}

###
# user request payment invoice
POST http://localhost:8080/api/event/5 HTTP/1.1
Content-Type: application/json
Authorization: {{login.response.headers.Authorization}}

{{getevent.response.body.embed}}
###
# user check in to invoice page, payment procedure
GET http://localhost:8080/api/payment/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInRpY2tldF9pZCI6IjEiLCJzdGF0dXMiOiJQcm9jZXNzaW5nIiwiZXhwIjoxNjE5OTgxMzM3LCJpYXQiOjE2MTk3MjIxMzcsImlzcyI6Im5hc2hpcmtyYSJ9._6JAaQqtbjV45jMlMAjt_G3obpRauK5grqAAR8qhdDQ HTTP/1.1
Content-Type: application/json
###
# user pay
POST http://localhost:8080/api/payment/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInRpY2tldF9pZCI6IjEiLCJzdGF0dXMiOiJQcm9jZXNzaW5nIiwiZXhwIjoxNjE5OTgxMzM3LCJpYXQiOjE2MTk3MjIxMzcsImlzcyI6Im5hc2hpcmtyYSJ9._6JAaQqtbjV45jMlMAjt_G3obpRauK5grqAAR8qhdDQ HTTP/1.1
Content-Type: application/json
###
# user cancel
POST http://localhost:8080/api/payment/cancel/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiMSIsInRpY2tldF9pZCI6IjEiLCJzdGF0dXMiOiJQcm9jZXNzaW5nIiwiZXhwIjoxNjE5OTgxMzM3LCJpYXQiOjE2MTk3MjIxMzcsImlzcyI6Im5hc2hpcmtyYSJ9._6JAaQqtbjV45jMlMAjt_G3obpRauK5grqAAR8qhdDQ HTTP/1.1
Content-Type: application/json
